{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloptima-k8s-agent.fullname" . }}
  labels:
    {{- include "cloptima-k8s-agent.labels" . | nindent 4 }}
rules:
  # Core resources
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/status
      - namespaces
      - pods
      - pods/status
      - services
      - endpoints
      - persistentvolumes
      - persistentvolumeclaims
      - events
      - resourcequotas
      - limitranges
    verbs: ["get", "list", "watch"]

  # Apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: ["get", "list", "watch"]

  # Batch resources
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  # Autoscaling resources
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

  # Autoscaling v2 resources (HPA v2)
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

  # VPA (if CRD exists)
  - apiGroups: ["autoscaling.k8s.io"]
    resources:
      - verticalpodautoscalers
    verbs: ["get", "list", "watch"]

  # Networking resources
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch"]

  # Storage resources
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["get", "list", "watch"]

  # Cluster metadata discovery
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-info"]
    verbs: ["get"]

  # Metrics
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
      - pods
    verbs: ["get", "list"]
{{- end }}
