{{- if and .Values.registration.enabled (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloptima-k8s-agent.secretName" . }}
  namespace: {{ include "cloptima-k8s-agent.namespace" . }}
  labels:
    {{- include "cloptima-k8s-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  INSTALLATION_TOKEN: {{ .Values.registration.installationToken | quote }}
{{- end }}
