{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloptima-k8s-agent.fullname" . }}
  namespace: {{ include "cloptima-k8s-agent.namespace" . }}
  labels:
    {{- include "cloptima-k8s-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cloptima-k8s-agent.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.metrics.path }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
