apiVersion: v2
name: cloptima-k8s-agent
description: Cloptima Kubernetes resource and metrics agent
type: application
version: 0.1.0
appVersion: "dev-latest"
keywords:
  - kubernetes
  - monitoring
  - cost-optimization
  - resource-tracking
home: https://cloptima.ai
maintainers:
  - name: Team Cloptima
  - email: hello@cloptima.ai
